### PR TITLE
Added critical interrupt enable feature.

### PR DESCRIPTION
**Pull request by JF-soft**
To enable this feature the user has to configure interrupt disable mask
portINTERRUPT_DISABLE_MASK to a value greater than 0x0000 in portmacro.h

Please review the code in portasm.asm and let me know what you think,

Regards, Jonatan.

### CODE REVIEW

**Comment by IvanZuy** [comment]
Hello Jonatan,

First of all, thank you for pull request.

I want to review it but there are some difficulties in doing it with PR as it is now.

- PR is a mix of code style changes along with new feature changes. It's very hard for me to review new feature changes because that mix. I haven't worked with C2000 architecture for 3 years. It would be much easier to review if I could see the clear diff for new feature changes only.
- Code style changes will never be accepted. This is holly war question and my position is that 100 chars line length is more than acceptable in 2020. I even moving towards 120 chars in other projects. I do realize that many people disagree and prefer 80 chars but this is the way.
- portASM.s file name change. I see that you fixed the typo in the file name. This is right thing to do but it has to be done in the separate commit. Now it looks like portasm.s is a new file and I don't see the diff for your changes. Another thing is that fine name change most likely broke example projects since they will be looking for old file name. All the projects which depend on porASM.s has to be changed in the same commit.
- Can you provide simplified example to test new feature? Detailed description would be also useful. If possible, I would like to understand more about why this feature is needed and which problem it solves.

Once again, thank you for PR, I deeply appreciate your time in doing it.
Best regards,
Ivan

**Comment by JF-soft** [comment]
No problem, I'll follow your suggestions and send a new pull request. The idea is to enable critical interrupts that do not use FreeRTOS API during portTICK_ISR, this allows the user to enable some interrupts as you mention in the issue you opened. The only problem is that using configMAX_SYSCALL_INTERRUPT_PRIORITY does not make sense for this architecture because there is no easy way to rearrange isr priority in software, so I think using a mask is more than enough.

**Comment by JF-soft** [comment]
I don't think changing the name of the .asm file is going to break anything, what is going to change examples is configuration of timer 2 that now is hidden from the user

**Comment by JF-soft** [comment]
Regarding coding style, it will never be a way, it is just a matter of taste, I would stick to whatever you like, because I think is more important to share the feature than to show what is the correct way of writting code.

**Pull request closed without merging**
